### ISSUE TITLE
Add v2.19.1 tag

### ISSUE THREAD

**Issue by dolfinus** [elixir-cldr/cldr#145]
Hello.

I've received notification from dependabot that new cldr version was released:
https://github.com/dolfinus/arkenston-backend/pull/45

But I've got an error while compiling one of my dependencies which is using "ru" locale. Cldr automatically downloads this locale from github, but it failing now:
https://github.com/dolfinus/arkenston-backend/pull/45/checks?check_run_id=2284878691
```
==> linguist
Compiling 5 files (.ex)

Error: 9.275 [error] Failed to download locale "ru" from https://raw.githubusercontent.com/elixir-cldr/cldr/v2.19.1/priv/cldr/locales/ru.json. HTTP Error: (404) 'Not Found'
Generating Linguist.Cldr for 3 locales named ["en", "root", "ru"] with a default locale named "en"

== Compilation error in file lib/linguist/cldr_backend.ex ==
** (RuntimeError) Locale definition was not found for ru
    (ex_cldr 2.19.1) lib/cldr/config/config.ex:1286: Cldr.Config.do_get_locale/2
    (ex_cldr 2.19.1) lib/cldr/config/config.ex:531: anonymous fn/2 in Cldr.Config.known_rbnf_locale_names/1
    (elixir 1.11.4) lib/enum.ex:3381: Enum.filter_list/2
    (elixir 1.11.4) lib/enum.ex:3382: Enum.filter_list/2
    (stdlib 3.14.1) erl_eval.erl:680: :erl_eval.do_apply/6
    (stdlib 3.14.1) erl_eval.erl:888: :erl_eval.expr_list/6
    (stdlib 3.14.1) erl_eval.erl:411: :erl_eval.expr/5
could not compile dependency :linguist, "mix compile" failed. You can recompile this dependency with "mix deps.compile linguist", update it with "mix deps.update linguist" or clean it with "mix deps.clean linguist"
The command '/bin/sh -c mix deps.get &&   mix deps.compile --force &&   mix compile --force' returned a non-zero code: 1
```

This is because there is no v2.19.1 tag in the repo. Could you please add it?

**Comment by kipcole9** [comment]
Very sorry for the inconvenience. Tagged now! Thanks for the repot.
