### ISSUE TITLE
Invalid AST on Elixir 1.18.0-rc.0

### ISSUE THREAD

**Issue by davydog187** [elixir-cldr/cldr#243]
For a module like this

```elixir
defmodule Sauron.Cldr do
  @moduledoc """
  Configuration for Cldr. The Elixir version of common unicode date/time/calendar functions.
  Kind of like a more modern Timex in my opinion.
  See: https://hexdocs.pm/ex_cldr
  """
  use Cldr, locales: ["en"]
end
```

On the v1.18.0-rc.0 release, it will fail with

```elixir
== Compilation error in file lib/sauron/cldr.ex ==
** (ArgumentError) tried to unquote invalid AST: %Cldr.Config{default_locale: :en, locales: [:en, :und], add_fallback_locales: false, backend: Sauron.Cldr, gettext: nil, data_dir: "/Users/davidlucia/dev/tvlabs/platform/sauron/_build/dev/lib/ex_cldr/priv/cldr", providers: [Cldr.DateTime, Cldr.Calendar, Cldr.Number, Cldr.List, Cldr.Unit, Cldr.Territory, Cldr.PersonName], precompile_number_formats: [], precompile_transliterations: [], precompile_date_time_formats: [], precompile_interval_formats: [], default_currency_format: nil, otp_app: nil, generate_docs: true, suppress_warnings: false, message_formats: %{}, force_locale_download: false, https_proxy: nil}
Did you forget to escape term using Macro.escape/1?
    (elixir 1.18.0-rc.0) src/elixir_quote.erl:542: :elixir_quote.argument_error/1
    (ex_cldr_numbers 2.33.3) lib/cldr/number/backend/decimal_formatter.ex:78: Cldr.Number.Backend.Decimal.Formatter.define_number_module/1
    (ex_cldr_numbers 2.33.3) lib/cldr/number/backend/compiler.ex:11: Cldr.Number.Backend.define_number_modules/1
    (ex_cldr 2.40.1) lib/cldr/config/config.ex:2658: anonymous fn/3 in Cldr.Config.define_provider_modules/1
    (elixir 1.18.0-rc.0) lib/enum.ex:2546: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_cldr 2.40.1) lib/cldr/config/config.ex:2656: Cldr.Config.define_provider_modules/1
    (ex_cldr 2.40.1) expanding macro: Cldr.Backend.Compiler.__before_compile__/1
    lib/sauron/cldr.ex:1: Sauron.Cldr (module)
```

**Comment by kipcole9** [comment]
This was [fixed](https://github.com/elixir-cldr/cldr_numbers/commit/fa8ad1354fc8395c0102666e7e07972adfc06c76) in `ex_cldr_numbers`. If you update to [ex_cldr_numbers 2.33.4](https://hex.pm/packages/ex_cldr_numbers/2.33.4) you should be good go.

Of course, please reopen if that is not the case.

**Comment by davydog187** [comment]
Thanks @kipcole9!
