### ISSUE TITLE
Error when compiling on Elixir 1.18 rc0

### ISSUE THREAD

**Issue by crbelaus** [elixir-cldr/cldr#245]
I am trying to compile my application with the new Elixir 1.18 rc0, but I am getting a compilation error on the Cldr module:

```
== Compilation error in file lib/my_app/cldr.ex ==
** (ArgumentError) tried to unquote invalid AST: %Cldr.Config{default_locale: :es, locales: [:ca, :de, :en, :es, :eu, :fr, :it, :nl, :pl, :pt, :und], add_fallback_locales: false, backend: MyApp.Cldr, gettext: MyAppWeb.Gettext, data_dir: "/Users/crbelaus/Developer/my_app/_build/dev/lib/ex_cldr/priv/cldr", providers: [Cldr.Number, Cldr.DateTime, Cldr.Territory, Cldr.Calendar, Cldr.Language, Cldr.LocaleDisplay], precompile_number_formats: ["#,##0.##", "#,##0.##%", "#,##0.####"], precompile_transliterations: [], precompile_date_time_formats: [], precompile_interval_formats: [], default_currency_format: nil, otp_app: nil, generate_docs: true, suppress_warnings: false, message_formats: %{}, force_locale_download: false, https_proxy: nil}
Did you forget to escape term using Macro.escape/1?
    (elixir 1.18.0-rc.0) src/elixir_quote.erl:542: :elixir_quote.argument_error/1
    (ex_cldr_numbers 2.33.3) lib/cldr/number/backend/decimal_formatter.ex:78: Cldr.Number.Backend.Decimal.Formatter.define_number_module/1
    (ex_cldr_numbers 2.33.3) lib/cldr/number/backend/compiler.ex:11: Cldr.Number.Backend.define_number_modules/1
    (ex_cldr 2.40.1) lib/cldr/config/config.ex:2658: anonymous fn/3 in Cldr.Config.define_provider_modules/1
    (elixir 1.18.0-rc.0) lib/enum.ex:2546: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_cldr 2.40.1) lib/cldr/config/config.ex:2656: Cldr.Config.define_provider_modules/1
    (ex_cldr 2.40.1) expanding macro: Cldr.Backend.Compiler.__before_compile__/1
    lib/my_app/cldr.ex:1: MyApp.Cldr (module)
```

The module has the following contents:

```elixir
defmodule MyApp.Cldr do
  use Cldr,
    default_locale: "es",
    gettext: MyAppWeb.Gettext,
    precompile_number_formats: ["#,##0.##", "#,##0.##%", "#,##0.####"],
    providers: [
      Cldr.Number,
      Cldr.Territory,
      Cldr.Language,
      Cldr.LocaleDisplay,
      Cldr.Calendar,
      Cldr.DateTime
    ]
end
```

**Comment by crbelaus** [comment]
I've tried to simplify the module to the maximum like this:

```elixir
defmodule MyApp.Cldr do
  use Cldr, default_locale: "es"
end
```

But I am still getting the same error

**Comment by LostKobrakai** [comment]
https://github.com/elixir-cldr/cldr/issues/243

**Comment by crbelaus** [comment]
Thanks @LostKobrakai

Confirmed that updating `ex_cldr_numbers` fixes this.
