### ISSUE TITLE
Breaks with Elixir 1.18

### ISSUE THREAD

**Issue by maikelthedev** [elixir-cldr/cldr#246]
Somehow the way the Cldr file in 

lib/project/cldr.ex to set the config

is written as in 

```elixir
defmodule Project.Cldr do
    use Cdlr,
     someoptions

end
```

is not compatible with Elixir 1.18

```
** (ArgumentError) tried to unquote invalid AST: %Cldr.Config{default_locale: :"en-001", locales: [:en, :"en-001", :und], add_fallback_locales: false, backend: Indie.Cldr, gettext: nil, data_dir: "/home/maikel/code/defloweredindie/_build/dev/lib/ex_cldr/priv/cldr", providers: [Cldr.Number, Cldr.Territory, Cldr.DateTime, Cldr.Calendar, Cldr.List, Cldr.PersonName, Cldr.Unit], precompile_number_formats: [], precompile_transliterations: [], precompile_date_time_formats: [], precompile_interval_formats: [], default_currency_format: nil, otp_app: nil, generate_docs: true, suppress_warnings: false, message_formats: %{}, force_locale_download: false, https_proxy: nil}
Did you forget to escape term using Macro.escape/1?
    (elixir 1.18.0) src/elixir_quote.erl:542: :elixir_quote.argument_error/1
    (ex_cldr_numbers 2.33.1) lib/cldr/number/backend/decimal_formatter.ex:77: Cldr.Number.Backend.Decimal.Formatter.define_number_module/1
    (ex_cldr_numbers 2.33.1) lib/cldr/number/backend/compiler.ex:11: Cldr.Number.Backend.define_number_modules/1
    (ex_cldr 2.40.1) lib/cldr/config/config.ex:2658: anonymous fn/3 in Cldr.Config.define_provider_modules/1
    (elixir 1.18.0) lib/enum.ex:2546: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_cldr 2.40.1) lib/cldr/config/config.ex:2656: Cldr.Config.define_provider_modules/1
    (ex_cldr 2.40.1) expanding macro: Cldr.Backend.Compiler.__before_compile__/1
    lib/indie/cldr.ex:1: Indie.Cldr (module)
```

I've tried with a simplified set of options and still get the same error. 

I'm not 100% sure whether here the error is of Cldr or Elixir 1.18, since the first line it points with code being wrong is from elixir itself. 

The project does compile with no issue on Elixir 1.17 and 1.16

**Comment by maikelthedev** [comment]
Got fixed by upgrading ex_cldr_numbers to 2.33.4
